/* config.h.  Generated by configure.  */
#define HAVE_STRERROR 1

#define HAVE_SETENV 1

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_ISATTY 1

#define HAVE_UNISTD_H 1

#define HAVE_GETPAGESIZE 1

/* #undef HAVE_MMAP */

#define HAVE_MEMCPY 1

#define HAVE_WAITPID 1

#define HAVE_SIGVEC 1

#define HAVE_SETSID 1

#define HAVE_STRFTIME 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_SYS_TERMIOS_H 1

#define HAVE_TERMIOS_H 1

#define HAVE_SYS_IOCTL_H 1

#define HAVE_RPC_RPC_H 1

/* #undef HAVE_RPC_RPCENT_H */

#define HAVE_SYS_SELECT_H 1

#define HAVE_SYS_FILE_H 1

/* #undef HAVE_MACHINE_REG_H */

#define HAVE_FTW_H 1

#define HAVE_NETDB_H 1

#define HAVE_LIBCRYPT 1

#define HAVE_ARPA_INET_H 1

#define HAVE_GRP_H 1

#define HAVE_RPC_PMAP_CLNT_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_SIGNAL_H 1

#define HAVE_STRSIGNAL 1

#define HAVE_SYS_SIGLIST 1

#define HAVE_CRYPT_H 1

#define HAVE_STDINT_H 1

#define HAVE_STDBOOL_H 1

/* #undef HAVE_SYS_FILIO_H */

/* #undef HAVE_KSTAT_H */

/* #undef NO_INET_ATON */

#define HAVE_STRUCT_ADDRINFO 1

#define HAVE_GAI_STRERROR 1

#define HAVE_FREEADDRINFO 1

#define HAVE_GETADDRINFO 1

#define HAVE_DIFFTIME 1

#define HAVE_GETNAMEINFO 1

#define HAVE_INET_NTOP 1

#define HAVE_STRUCT_IN6_ADDR 1

#define HAVE_STRUCT_SOCKADDR_IN6 1

#define HAVE_STRUCT_SOCKADDR_STORAGE 1

#define HAVE_FCVT 1

#define HAVE_ECVT 1

#define HAVE_GCVT 1

#define HAVE_STRCASECMP 1

/* #undef HAVE_MDNS */

/* #undef HAVE_DNSREGISTRATION */

/* #undef HAVE_HOWL */

/* OS specific */
/* #undef solaris */

/* Options */
/* #undef HAVE_LIBWRAP */
/* #undef LIBWRAP */
/* #undef LABELED_NET */

/* #undef HAVE_LOADAVG */

/* #undef uint16_t */
/* #undef uint32_t */
/* #undef uint64_t */
/* #undef gid_t */
/* #undef uid_t */
/* #undef socklen_t */
/* #undef rlim_t */

/* Versioning Information */
#define XINETD_VERSION "xinetd Version 2.3.15"
#define MISC_VERSION   "MISC Version 1.2.2"
#define PSET_VERSION   "PSET Version 1.2.0"
#define SIO_VERSION    "SIO Version 1.6.2"
#define STR_VERSION    "STR Version 1.4.1"
#define TIMER_VERSION  "TIMER Version 1.2.2"
#define XLOG_VERSION   "XLOG Version 1.1.2"
